### ISSUE TITLE
Refactor Docker image build process

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#1153]
### Current build process
Upon a merge on the `master` branch or a manual trigger, Docker Hub:
- clones the Git repository on the `master` branch
- builds the `master` image from `docker/alpine/Dockerfile.master`
- builds the `latest` image from `docker/alpine/Dockerfile.latest`
- builds the `stable` image from `docker/debian/Dockerfile.stable`

The images are currently built by using the binary release archives, that come with all PHP and NodeJS dependencies bundled (if applicable).

The drawbacks are that:
- each time a commit is merged on `master`, *all images* are built
- there is no Dockerfile to build an image from the Git sources, hence:
    - there is no straightforward way to build an image for a given Git revision (e.g. tag)
    - there are no images for given Shaarli versions

### Suggested build process
- build Docker images using sources from the local Git repository
- maintain a single Dockerfile per branch (and per architecture), located at the root of the repository
- update Docker Hub triggers to build branch- and tag-specific images

This will provide a much simpler way of dealing with Docker images, and allow using Docker to run PRs.

### TODO
- [x] #1156 update the current `stable` branch (`v0.8`) and its Docker Hub trigger
    - [x] release `v0.8.x`
    - [x] update `stable`
- [x] #1157 update the current `latest` branch (`v0.9`) and its Docker Hub trigger
    - [x] release `v0.9.x`
    - [x] update `latest`
- [x] #1158 update the `master` branch and its Docker Hub trigger
- [x] update documentation
    - [x] Docker image list
    - [x] Docker test images

**Comment by virtualtam** [comment]
[v0.8.7](https://github.com/shaarli/Shaarli/releases/tag/v0.8.7) and [v0.9.7](https://github.com/shaarli/Shaarli/releases/tag/v0.9.7) have been released, and fresh images are available from Docker Hub :)
