### ISSUE TITLE
Drop support for PHP 5.6 and 7.0

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#1249]
### PHP EoL
- 5.6: 2018-12-31
- 7.0: 2018-12-03

See:
- [Supported versions](https://secure.php.net/supported-versions.php)
- [Unsupported Branches](https://secure.php.net/eol.php)

### TODO
- [x] bump Composer requirements
- [ ] update `index.php`:
    - [ ] documentation - maybe we can remove the information from the file header as it is advertised elsewhere?
    - [ ] version check
- [x] update documentation:
    - [x] server requirements
- [x] update Travis test environments

### Trivia
This is the first time (in Shaarli history) that a PHP version (7.0) reaches its end-of-life before a previous version (5.6).

**Comment by ArthurHoaro** [comment]
Oh that's great! I would add that we should mention somewhere that Shaarli is usable on PHP 5.6 with the latest 10.x. Not sure if we should put it in the download page, or the index, but somewhere more visible than the server requirements page.

**Comment by lutzhorn** [comment]
PHP 7.0.x is the default version on the widely deployed Ubuntu 16.04 LTS. Dropping support for this PHP version would be bad news for these deployments.

**Comment by virtualtam** [comment]
Hi @lutzhorn!

Please note that dropping active support for EoL PHP versions does not necessarily means that it won't work with those versions. As we are very few developers working on Shaarli, our main focus is to provide support for officially maintained releases.

We will happily accept contributions and bug fixes that help maintaining compatibility with old(er) versions as long as it's not a drag for new releases :)

In addition to using a recent distribution or the Docker images, it's also worth mentioning that it is possible to run newer PHP versions through third-party package repositories, such as:
- Ondřej Surý's repositories for [Debian](https://deb.sury.org/) and [Ubuntu](https://launchpad.net/~ondrej/+archive/ubuntu/php/)
- [Remi's RPM repository](https://blog.remirepo.net/) for RHEL/CentOS
