### ISSUE TITLE
[Announcements] Releases / Roadmap

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#353]
## Foreword

This thread serves several purposes:
- as a hub to reference active discussion threads;
- as a board for maintainers to announce upcoming/major changes.

It may come handy for both users and 3rd-party developers, to keep in touch with what's going under the hood.

Don't hesitate to contribute to active threads, comment issues and pull requests -if anything's missing, feel free to raise a new issue!
In case you'd like to contribute, please raise an issue first, so we can get you started quickly :)
## Discussion threads
- #106 - Original ideas / Fixme
- #44 - General discussion (archived)
- #308 - General discussion
### Background tasks
- [ ] #324 - Code refactoring
- [x] #71 - Test coverage
- [ ] #95 - Coding convention compliance

#### [v0.6.x](https://github.com/shaarli/Shaarli/milestones/0.6.0) - Core plugins
- [x] #275 - Plugin system
- [x] #378 - Plugin administration UI

#### [v0.7.x](https://github.com/shaarli/Shaarli/milestones/0.7.0) - Minor changes
- [x] #247 - Private link statistics
- [x] #273 - Templates for Atom & RSS feeds

#### [v0.8.0](https://github.com/shaarli/Shaarli/milestones/0.8.0) - Configuration manager
- [x] #570 - Introduce a configuration manager
- [x] #607 - Introduce a generic Netscape bookmark parser (and Composer dependency management)

#### [v0.9.x](https://github.com/shaarli/Shaarli/milestones/0.9.0) - REST API & template management

REST API:
- [x] #599 - Drop PHP 5.3/5.4 compatibility
- [x] #609 - Expose an API for Shaarli
- [x] #659 - `init()` function for plugins
- [x] #663 - Add a CHANGELOG.md and adopt a formatting convention for release notes

Theming _(see [template](https://github.com/shaarli/Shaarli/issues?utf8=%E2%9C%93&q=label%3Atemplate+)-related issues)_:
- [x] #22, #502, #705, #732 - Theme selection from the configuration page
- [x] #266 - Page template & CSS rewrite
- [x] #312 - Documentation on ReadTheDocs

#### [v0.10.x](https://github.com/shaarli/Shaarli/milestones/0.10.0) - Continuous Integration tools / UI
- [ ] #185 - Administration tools
- [ ] #345 - Thumbnails refactoring and improvements.
- [ ] #258 & #226 - Template semantics
- [ ] #160 & #161 - _Daily_ view

#### [v0.11.x](https://github.com/shaarli/Shaarli/milestones/0.11.0) - Stabilization / Pre-release
TBA

#### [v1.0.x](https://github.com/shaarli/Shaarli/milestones/1.0.0) - Stable release
TBA

**Comment by ArthurHoaro** [comment]
**To theme maintainers:** v0.6 will bring important changes to templates. 

Please use [Plugin system: Guide for template designer](https://github.com/shaarli/Shaarli/wiki/Plugin-System#guide-for-template-designer) documentation to update your theme.

**Comment by ArthurHoaro** [comment]
[v0.6.0](https://github.com/shaarli/Shaarli/releases/tag/v0.6.0) containing the plugin system has been released. 

The `stable` branch still points to v0.5.4.

**Comment by ArthurHoaro** [comment]
v0.6.3 has been release.

**To theme maintainers:** there is 2 new template pages that you need to add, [pluginsadmin.html](https://github.com/shaarli/Shaarli/blob/master/tpl/pluginsadmin.html) ([documentation](https://github.com/shaarli/Shaarli/wiki/Plugin-System#plugin-administration) and #388 ) and [404.html](https://github.com/shaarli/Shaarli/blob/master/tpl/404.html).

v0.6.4 will be the last v0.6.x version, containing search features. The `stable` branch will point to v0.6.4 when it's released.

**Comment by ArthurHoaro** [comment]
[v0.6.4](https://github.com/shaarli/Shaarli/releases/tag/v0.6.4) has been released. It's the last `v0.6.x` (except big regression) and is the new `stable` version.

**Theme maintainers**: search results has been updated.

**Comment by virtualtam** [comment]
Note to **plugin** and **theme** maintainers: `v0.8.x` will bring major changes to how user settings are stored and handled, see:
- PR #570 - Introduce a configuration manager
- temporary PR #591 - Config manager documentation changes

**Comment by ArthurHoaro** [comment]
[v0.8.0](https://github.com/shaarli/Shaarli/releases/tag/v0.8.0) has been released, including major changes. `v0.7.0` is now the new stable version.

For v0.8.0, make sure to download `*-full` archive to include Composer dependencies, or follow our [installation guide](https://github.com/shaarli/Shaarli/wiki/Download-and-Installation).

**Comment by virtualtam** [comment]
Note to **theme** and **template** developers: #732 introduces template selection from the Shaarli configuration page (see also #22, #502, #705)

**Comment by ArthurHoaro** [comment]
[v0.9.0](https://github.com/shaarli/Shaarli/releases/tag/v0.9.0) has been released! This major version contains a lot of changes, especially regarding themes, due to the introduction of the new theme.

As always, please report any issue you see.

**Comment by virtualtam** [comment]
@nodiscc @ArthurHoaro there was an intruder `help` tag on the Git repository, please check it's absent from your forks and local Git workspaces :) 👾

**Comment by virtualtam** [comment]
[v0.9.1](https://github.com/shaarli/Shaarli/releases/tag/v0.9.1) has been released! This minor version brings a bunch of fixes and enhancements, along with the migration of the documentation from GitHub Wiki to ReadTheDocs: https://shaarli.readthedocs.io/en/master/.

**Comment by nodiscc** [comment]
This thread has not been updated for a while, does it make sense to close it? Here are a few places where users can follow ongoing development of Shaarli:

 - [Releases](https://github.com/shaarli/Shaarli/releases) ([ATOM feed](https://github.com/shaarli/Shaarli/releases.atom))
- [Milestones](https://github.com/shaarli/Shaarli/milestones)
- [Projects](https://github.com/shaarli/Shaarli/projects)

**Comment by virtualtam** [comment]
I agree that we can close this issue as it is redundant with the _milestones_ page and the versioned _changelog_.

**Comment by nodiscc** [comment]
https://github.com/shaarli/Shaarli/blob/master/CHANGELOG.md
