### ISSUE TITLE
Introduce an ApplicationUtils class to group Shaarli (application) utils

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#372]
Follow-up to #333 - Refactor HTTP / Url functions
Relates to #324 - Memo: code refactoring
### Miscellaneous
- [ ] Add an error page template & Router entry
  - [ ] Display UID / GID information - see [POSIX](http://php.net/manual/en/ref.posix.php) functions
### Shaarli update checks
- [x] #390 - Refactor and move update checks
- [x] #394 - Allow choosing the GIt branch used for checks (current: `master`, safer: `stable`)
### PHP version checks
- [x] #389 - Move from the generic utils script
### Setup/install form
- [ ] Add a page / template for the install form
- [ ] Move the timezone form to a template
### Read/write permissions, file/folder ownership
- [ ] #40 - Require write permissions only for relevant directories
  - [x] #375 - install: check file/directory permissions for Shaarli resources
  - [ ] Add a permission check page & template
  - [ ] Redirect to an error page if the datastore is not writable
  - [ ] Add a Tools entry to check permissions

**Comment by virtualtam** [comment]
Closing as stale / obsolete
