### ISSUE TITLE
Introduce a generic Netscape bookmark parser

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#607]
## `TL;DR` - Shaarli now requires Composer
- this change introduces the usage of [Composer](https://getcomposer.org/) to manage PHP dependencies
- if you run Shaarli from the `master` branch, you _need_ to install Composer, either system-wide or for your local user
- once installed, use it to install/update PHP dependencies

Example usage:

```bash
$ cd path/to/shaarli

# if Composer is installed system-wide
$ composer update --no-dev

# if Composer is installed for your local user only
$ php path/to/composer.phar update --no-dev
```

## Bio
- work started at #493 - bookmarks: refactor the import functions (abandoned)
- we stumbled upon the generic https://github.com/kafene/netscape-bookmark-parser
    - it's been forked and improved at https://github.com/shaarli/netscape-bookmark-parser
    - available through Composer/Packagist at https://packagist.org/packages/kafene/netscape-bookmark-parser#dev-master
    - https://github.com/shaarli/netscape-bookmark-parser/issues/15 and https://github.com/kafene/netscape-bookmark-parser/issues/6 raised to tag a new release

### `v0.8.0`
- [x] reference `netscape-bookmark-parser` as a Composer dependency
    - [x] create a tag on the fork - https://github.com/shaarli/netscape-bookmark-parser/releases/tag/shaarli-v0.8.0
    - [x] #608 - reference this tagged version from Composer as a [VCS repository](https://getcomposer.org/doc/05-repositories.md#vcs)
    - [x] #632 - reference our Packagist repository
- [x] #608 - add a Makefile target to generate a Shaarli release archive containing Composer dependencies
- [x] #612 - replace the current parser with `netscape-bookmark-parser`
- [x] update Shaarli demo deployment scripts (see https://github.com/composer/composer/issues/5592)
- [x] #633 #634 - update Dockerfiles for the `master` branch
- [x] update user documentation (Git+Composer vs. archive)
    - [x] https://github.com/shaarli/Shaarli/wiki/Download
    - [x] https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration
    - [x] https://github.com/shaarli/Shaarli/wiki/Server-requirements
- [x] update developer/maintainer documentation
    - [x] https://github.com/shaarli/Shaarli/wiki/3rd-party-libraries
    - [x] https://github.com/shaarli/Shaarli/wiki/Release-Shaarli
- [x] #645 display an error message if 3rd-party dependencies are missing

### Post-release tasks
- [x] #638 - update Dockerfile for the `stable` branch
- [x] update user and developer documentation

**Comment by ArthurHoaro** [comment]
- [ ] Update the release doc.

That's nice, and also a great step toward a proper dependency management.

**Comment by virtualtam** [comment]
Moving to `v0.8.1` as some points require a new Shaarli version to be released in order to be addressed

**Comment by ArthurHoaro** [comment]
I think everything has been addressed, can we close?

**Comment by virtualtam** [comment]
Functionally, yes, though I'd like to wait for a new release to be marked as stable to check Docker image generation :)

**Comment by virtualtam** [comment]
Finally closing, I'll raise new issues in case further modifications are required :)
